### ISSUE TITLE
Swift for iPhone

### ISSUE THREAD

**Issue by Catherine-zi** [FabrizioBrancati/SwiftyBot#10]
Is there a Swift for iPhone of the Demo?

**Comment by FabrizioBrancati** [comment]
Why do you want an iPhone Demo?
This code is meant to be run on a server, what do you expect from an iPhone Demo?

I just want to know your point of view, maybe will be useful for others 😄

**Comment by Catherine-zi** [comment]
First of all,Thank you for your reply.
We're going to do an application that includes chat functionality.
I'd like to find telegram swift version of the SDK, but I can't find it.
Maybe you can tell me more about telegram.
If my description is ambiguous, please forgive me.

**Comment by Catherine-zi** [comment]
First of all,Thank you for your reply.
We're going to do an application that includes chat functionality.
I'd like to find telegram swift version of the SDK, but I can't find it.
Maybe you'll know more about the telegram, so I want to try my luck.
If my question is an interruption to you, please forgive me.

**Comment by Catherine-zi** [comment]
First of all,Thank you for your reply.
We're going to do an application that includes chat functionality.
I'd like to find telegram swift version of the SDK, but I can't find it.
Maybe you'll know more about the telegram, so I want to try my luck.
If my question is an interruption to you, please forgive me.

**Comment by FabrizioBrancati** [comment]
I'm sorry but is a bit different, I'm only handling [Bot Telegram APIs](https://core.telegram.org/bots/api).
[This project](https://github.com/overtake/TelegramSwift) may be useful to you
