### ISSUE TITLE
Can not run this

### ISSUE THREAD

**Issue by n0an** [FabrizioBrancati/SwiftyBot#5]
When I run this using XCode, or vapor run command, I got this:
The default hash should be replaced before using in production.
The default cipher should be replaced before using in production.
Missing secret or token keys!

I created app.json file with secret and token provided

**Comment by FabrizioBrancati** [comment]
The Vapor's warnings can be ignored since SwiftyBot doesn't use hash or cipher.
Where did you create the `app.json` file? It must be inside the `secrets` folder

**Comment by n0an** [comment]
I've figured out how to run. Created PR with fix for Config/secrets/README.md about app.json format

**Comment by FabrizioBrancati** [comment]
Great! Thanks 👍

**Comment by FabrizioBrancati** [comment]
Merged! 🎉
